import 'dart:convert';
import 'dart:io';

import 'package:lebanon_places/features/places/data/google_places_service.dart';
import 'package:lebanon_places/features/places/data/places_repository.dart';
import 'package:lebanon_places/features/places/domain/place_model.dart';

Future<void> main() async {
  final service = GooglePlacesService();
  final places = DemoPlacesRepository.allDemoPlaces;

  stdout.writeln('Resolving Google Place IDs for ${places.length} places...');
  final rows = <Map<String, dynamic>>[];

  for (var i = 0; i < places.length; i++) {
    final place = places[i];
    stdout.writeln('[${i + 1}/${places.length}] ${place.name}');
    final resolved = await service.resolvePlace(place);
    final confidence = _confidence(place, resolved);
    rows.add({
      'id': place.id,
      'name': place.name,
      'region': place.region,
      'address': place.address,
      'existingLat': place.latitude,
      'existingLng': place.longitude,
      'resolvedName': resolved?.name,
      'resolvedAddress': resolved?.formattedAddress,
      'resolvedPlaceId': resolved?.placeId,
      'resolvedLat': resolved?.latitude,
      'resolvedLng': resolved?.longitude,
      'confidence': confidence.name,
      'status': resolved?.placeId == null ? 'not_found' : 'resolved',
    });
  }

  final docsDir = Directory('docs');
  if (!docsDir.existsSync()) {
    docsDir.createSync(recursive: true);
  }

  final jsonFile = File('docs/place_id_resolution_report.json');
  jsonFile.writeAsStringSync(
    const JsonEncoder.withIndent('  ').convert(rows),
  );

  final mdFile = File('docs/place_id_resolution_report.md');
  mdFile.writeAsStringSync(_buildMarkdown(rows));

  final snippetFile = File('docs/place_id_patch_snippets.txt');
  snippetFile.writeAsStringSync(_buildPatchSnippets(rows));

  final resolvedCount = rows.where((r) => r['resolvedPlaceId'] != null).length;
  final highConfidence =
      rows.where((r) => r['confidence'] == Confidence.high.name).length;
  final mediumConfidence =
      rows.where((r) => r['confidence'] == Confidence.medium.name).length;
  final lowConfidence =
      rows.where((r) => r['confidence'] == Confidence.low.name).length;

  stdout.writeln('');
  stdout.writeln('Done.');
  stdout.writeln('Resolved IDs: $resolvedCount / ${places.length}');
  stdout.writeln(
      'Confidence: high=$highConfidence, medium=$mediumConfidence, low=$lowConfidence');
  stdout.writeln('Generated files:');
  stdout.writeln('- docs/place_id_resolution_report.json');
  stdout.writeln('- docs/place_id_resolution_report.md');
  stdout.writeln('- docs/place_id_patch_snippets.txt');
  stdout.writeln('');
  stdout.writeln(
      'Next: review low-confidence rows, then copy confirmed snippets into places_repository.dart');
}

enum Confidence { high, medium, low }

Confidence _confidence(PlaceModel place, ResolvedPlaceData? resolved) {
  if (resolved == null || resolved.placeId == null) return Confidence.low;
  final placeName = place.name.trim().toLowerCase();
  final resolvedName = (resolved.name ?? '').trim().toLowerCase();
  final region = (place.region ?? '').trim().toLowerCase();
  final resolvedAddress = (resolved.formattedAddress ?? '').trim().toLowerCase();

  final nameExact = resolvedName == placeName;
  final nameContains =
      resolvedName.contains(placeName) || placeName.contains(resolvedName);
  final regionMatch = region.isEmpty || resolvedAddress.contains(region);

  if (nameExact && regionMatch) return Confidence.high;
  if (nameContains && regionMatch) return Confidence.medium;
  return Confidence.low;
}

String _buildMarkdown(List<Map<String, dynamic>> rows) {
  final buffer = StringBuffer();
  buffer.writeln('# Place ID Resolution Report');
  buffer.writeln('');
  buffer.writeln(
      'Generated by `tool/fetch_official_place_ids.dart`. Review medium/low confidence rows manually.');
  buffer.writeln('');
  buffer.writeln(
      '| ID | Name | Region | Status | Confidence | Resolved Name | Resolved Address | Place ID |');
  buffer.writeln(
      '|---|---|---|---|---|---|---|---|');
  for (final row in rows) {
    buffer.writeln(
      '| ${row['id']} | ${_safe(row['name'])} | ${_safe(row['region'])} | ${row['status']} | ${row['confidence']} | ${_safe(row['resolvedName'])} | ${_safe(row['resolvedAddress'])} | ${_safe(row['resolvedPlaceId'])} |',
    );
  }
  return buffer.toString();
}

String _buildPatchSnippets(List<Map<String, dynamic>> rows) {
  final buffer = StringBuffer();
  buffer.writeln(
      'Copy these per-place fields into each PlaceModel in places_repository.dart');
  buffer.writeln('');
  for (final row in rows) {
    if (row['resolvedPlaceId'] == null) continue;
    buffer.writeln('// ${row['id']} - ${row['name']}');
    buffer.writeln("googlePlaceId: '${row['resolvedPlaceId']}',");
    if (row['resolvedLat'] != null && row['resolvedLng'] != null) {
      buffer.writeln('latitude: ${row['resolvedLat']},');
      buffer.writeln('longitude: ${row['resolvedLng']},');
    }
    buffer.writeln('');
  }
  return buffer.toString();
}

String _safe(Object? value) {
  if (value == null) return '-';
  final s = value.toString().replaceAll('|', '\\|').replaceAll('\n', ' ');
  return s.isEmpty ? '-' : s;
}
